name: serialize
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  intl: ^0.17.0
  args: any
  process_run: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
